project:
  type: website
  output-dir: docs

website:
  title: "Jessica M. da Silva"
  site-url: "https://jessmds.github.io/"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "People"
        href: team.qmd
      - text: "Opportunities"
        href: opportunities.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme:
      - cosmo
      - custom.scss
    include-in-header:
      text: |
        <meta name="google-site-verification" content="EVWSVHSD6WuP88xZl-ilEXNuiO2-OHlYOPzbSMMLSSg" />
    page-layout: full
    link-external-newwindow: true

